// ============================================================
// TRANSLATIONS — EN / AM (Amharic)
// Matches the i18n strings from MP.html exactly
// ============================================================

export const TRANSLATIONS = {
  en: {
    city_label: 'Addis Ababa City',
    search_placeholder: 'Search menu...',
    fasting: 'Fasting',
    explore: 'Explore Our',
    delicious_menu: 'Delicious Menu',
    sort_popular: 'Popular',
    sort_price_low: 'Price: Low to High',
    sort_price_high: 'Price: High to Low',
    sort_name: 'A to Z',
    back: 'Back',
    your_tray: 'Your Tray',
    clear: 'Clear',
    table_number: 'Table Number',
    split_among: 'Split among',
    people: 'people',
    extra_instructions: 'Extra Instructions',
    instructions_placeholder: 'e.g. No onions, Extra cheese...',
    subtotal: 'Subtotal',
    service: 'Service (10%)',
    total: 'Total',
    payment_method: 'Payment Method',
    cash: 'Cash',
    waiter: 'Waiter',
    pay_to: 'Pay to this account',
    copy_number: 'Copy Number',
    send_order: 'Send Order to Kitchen',
    menu_nav: 'Menu',
    tray_nav: 'Tray',
    crust_type: 'Crust Type',
    select_size: 'Select Size',
    order_status: 'Order Ticket',
    new_order: 'Start New Order',
    order_placed: 'Order Placed!',
    processing: 'Processing...',
    popular: '★ Popular',
    sold_out: 'Sold Out',
    limited: 'Limited',
    add_to_tray: 'Add',
    view_tray: 'View Tray',
    no_items: 'No items found',
    empty_tray: 'Your tray is empty',
    browse_menu: 'Browse Menu',
    popular_picks: '🔥 Popular Picks',
    error_table: 'Please enter a table number',
    error_payment: 'Please select a payment method',
    per_person: 'per person',
    tracking_order: 'Tracking your order...',
    order_number: 'Order #',
    table: 'Table',
    est_time: 'Est. 25–35 mins',
    status_received: 'Order Received',
    status_accepted: 'Accepted by Kitchen',
    status_preparing: 'Being Prepared',
    status_ready: 'Ready for Pickup',
    status_completed: 'Completed',
    status_rejected: 'Order Rejected',
  },
  am: {
    city_label: 'አዲስ አበባ ከተማ',
    search_placeholder: 'ምናሌ ይፈልጉ...',
    fasting: 'ጾም',
    explore: 'የኛን ምርጥ',
    delicious_menu: 'ምናሌ ይመልከቱ',
    sort_popular: 'ታዋቂ',
    sort_price_low: 'ዋጋ፦ ከዝቅተኛ ወደ ከፍተኛ',
    sort_price_high: 'ዋጋ፦ ከከፍተኛ ወደ ዝቅተኛ',
    sort_name: 'ከሀ እስከ ፐ',
    back: 'ተመለስ',
    your_tray: 'ትሪዎ',
    clear: 'አጥፋ',
    table_number: 'የጠረጴዛ ቁጥር',
    split_among: 'ሂሳብ አካፍል',
    people: 'ሰዎች',
    extra_instructions: 'ተጨማሪ መመሪያ',
    instructions_placeholder: 'ለምሳሌ፦ ያለ ሽንኩርት፣ ተጨማሪ አይብ...',
    subtotal: 'ድምር',
    service: 'አገልግሎት (10%)',
    total: 'ጠቅላላ',
    payment_method: 'የክፍያ ዘዴ',
    cash: 'ጥሬ ገንዘብ',
    waiter: 'አስተናጋጅ',
    pay_to: 'ወደዚህ ሂሳብ ይክፈሉ',
    copy_number: 'ቁጥር ቅዳ',
    send_order: 'ትዕዛዝ ለኩሽና ላክ',
    menu_nav: 'ምናሌ',
    tray_nav: 'ትሪ',
    crust_type: 'የዳቦ አይነት',
    select_size: 'መጠን ይምረጡ',
    order_status: 'የትዕዛዝ ሁኔታ',
    new_order: 'አዲስ ትዕዛዝ ጀምር',
    order_placed: 'ትዕዛዝ ተልኳል!',
    processing: 'በሂደት ላይ...',
    popular: '★ ታዋቂ',
    sold_out: 'አልቋል',
    limited: 'ውስን',
    add_to_tray: 'አስቀምጥ',
    view_tray: 'ትሪ ይመልከቱ',
    no_items: 'ምንም ምርት አልተገኘም',
    empty_tray: 'ትሪዎ ባዶ ነው',
    browse_menu: 'ምናሌ ይመልከቱ',
    popular_picks: '🔥 ተወዳጅ ምርቶች',
    error_table: 'እባክዎ የጠረጴዛ ቁጥር ያስገቡ',
    error_payment: 'እባክዎ የክፍያ ዘዴ ይምረጡ',
    per_person: 'ለሰው',
    tracking_order: 'ትዕዛዝ በክትትል ላይ...',
    order_number: 'ትዕዛዝ #',
    table: 'ጠረጴዛ',
    est_time: 'ቅ. 25–35 ደቂቃ',
    status_received: 'ትዕዛዝ ተቀብሏል',
    status_accepted: 'ኩሽና ተቀብሏል',
    status_preparing: 'በዝግጅት ላይ',
    status_ready: 'ዝግጁ ነው',
    status_completed: 'ተጠናቋል',
    status_rejected: 'ትዕዛዝ ተቀናሷል',
  },
};

export const PAYMENT_ACCOUNTS = {
  telebirr: { number: '093 400 9937', name: 'MUAZ' },
  cbe:      { number: '1000739055718', name: 'Umer' },
  chapa:    { number: '0989',       name: 'Pizza Hut Chapa' },
  cash:     { number: 'Pay to Waiter', name: 'Cash Payment at Table' },
};

export const VAT_RATE = 0.15;
export const SERVICE_RATE = 0.10;
export const STUFFED_CRUST_PRICE_MEDIUM = 795;
export const STUFFED_CRUST_PRICE_LARGE = 1040;

export const BRANCH_OPTIONS = [
  '4 Kilo',
  'Lebu',
  'Morning Star Mall',
  'Bole Bulbula',
  'Century Mall',
  'Sarbet Boran Complex',
];
