import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://mdacgaihccmghhonriog.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kYWNnYWloY2NtZ2hob25yaW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxMDc1MDEsImV4cCI6MjEwMDY4MzUwMX0.CTYGCNZM5lUtZx7C3QEy0I8v6ZyhxAK-zCYq0Eh_L5M';

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const CAT_VEG = 'a0ee1c23-1111-2222-3333-444444444441';
const CAT_MEAT = 'a0ee1c23-1111-2222-3333-444444444442';
const CAT_CHICKEN = 'a0ee1c23-1111-2222-3333-444444444443';
const CAT_FASTING = 'a0ee1c23-1111-2222-3333-444444444444';
const CAT_SIDES = 'a0ee1c23-1111-2222-3333-444444444445';
const CAT_SPECIALS = 'a0ee1c23-1111-2222-3333-444444444446';
const CAT_DRINKS = 'a0ee1c23-1111-2222-3333-444444444447';

const ITEMS_DATA = [
  // --- VEG PIZZA ---
  {
    category_id: CAT_VEG,
    name: 'Margherita Pizza',
    description: 'Tomato Sauce, Mozzarella Cheese, Tomato',
    base_price: 770,
    item_type: 'pizza',
    prices_json: { small: 495, medium: 770, large: 1120 },
    dietary_tags: ['vegetarian'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_VEG,
    name: 'Cheese Pizza',
    description: 'Tomato Sauce, Mozzarella Cheese, Cheddar Cheese',
    base_price: 740,
    item_type: 'pizza',
    prices_json: { small: 475, medium: 740, large: 1100 },
    dietary_tags: ['vegetarian'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_VEG,
    name: 'Hot & Spicy Veg',
    description: 'Tomato Sauce, Mozzarella Cheese, Onion, Capsicum, Green Chilli',
    base_price: 875,
    item_type: 'pizza',
    prices_json: { small: 550, medium: 875, large: 1315 },
    dietary_tags: ['vegetarian', 'spicy'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_VEG,
    name: 'Mushroom Lovers\'',
    description: 'Tomato Sauce, Mozzarella Cheese, Mushroom, Olives',
    base_price: 940,
    item_type: 'pizza',
    prices_json: { small: 585, medium: 940, large: 1245 },
    dietary_tags: ['vegetarian'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_VEG,
    name: 'Tropical Veggie',
    description: 'Tomato Sauce, Mozzarella Cheese, Onion, Capsicum, Pineapple',
    base_price: 905,
    item_type: 'pizza',
    prices_json: { small: 585, medium: 905, large: 1390 },
    dietary_tags: ['vegetarian'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_VEG,
    name: 'Veggie Supreme',
    description: 'Tomato Sauce, Mozzarella Cheese, Onion, Capsicum, Tomato & Olives',
    base_price: 830,
    item_type: 'pizza',
    prices_json: { small: 540, medium: 830, large: 1245 },
    dietary_tags: ['vegetarian'],
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=600&q=80',
  },

  // --- MEAT PIZZA ---
  {
    category_id: CAT_MEAT,
    name: 'Hawaiian Pizza',
    description: 'Tomato Sauce, Mozzarella Cheese, Turkey Ham, Pineapple',
    base_price: 965,
    item_type: 'pizza',
    prices_json: { small: 700, medium: 965, large: 1315 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_MEAT,
    name: 'Italian Meat',
    description: 'Tomato Sauce, Mozzarella Cheese, Italian Meat Roll, Onion, Tomato, Chicken',
    base_price: 1070,
    item_type: 'pizza',
    prices_json: { small: 775, medium: 1070, large: 1535 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_MEAT,
    name: 'Meat Lovers\'',
    description: 'Tomato Sauce, Mozzarella Cheese, Pepperoni, Turkey Ham, Beef',
    base_price: 1150,
    item_type: 'pizza',
    prices_json: { small: 765, medium: 1150, large: 1535 },
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_MEAT,
    name: 'Pepperoni Lovers\'',
    description: 'Tomato Sauce, Mozzarella Cheese, Pepperoni',
    base_price: 965,
    item_type: 'pizza',
    prices_json: { small: 685, medium: 965, large: 1410 },
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_MEAT,
    name: 'BBQ Double Meat',
    description: 'Tomato Sauce, Mozzarella Cheese, Turkey Ham, Beef',
    base_price: 1150,
    item_type: 'pizza',
    prices_json: { small: 765, medium: 1150, large: 1535 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_MEAT,
    name: 'Super Supreme',
    description: 'Tomato Sauce, Mozzarella Cheese, Beef, Pepperoni, Turkey Ham, Onion, Capsicum, Olives',
    base_price: 1200,
    item_type: 'pizza',
    prices_json: { small: 795, medium: 1200, large: 1535 },
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80',
  },

  // --- CHICKEN PIZZA ---
  {
    category_id: CAT_CHICKEN,
    name: 'Hot & Spicy Chicken',
    description: 'Tomato Sauce, Mozzarella Cheese, Chicken, Onion, Tomato, Green Chilli',
    base_price: 1055,
    item_type: 'pizza',
    prices_json: { small: 665, medium: 1055, large: 1550 },
    dietary_tags: ['spicy'],
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_CHICKEN,
    name: 'Sweet Chilli Chicken',
    description: 'Tomato Sauce, Mozzarella Cheese, Chicken',
    base_price: 1070,
    item_type: 'pizza',
    prices_json: { small: 700, medium: 1070, large: 1505 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_CHICKEN,
    name: 'BBQ Chicken',
    description: 'Tomato Sauce, Mozzarella Cheese, Turkey Ham, Chicken',
    base_price: 1165,
    item_type: 'pizza',
    prices_json: { small: 740, medium: 1165, large: 1535 },
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_CHICKEN,
    name: 'Chicken & Mushroom',
    description: 'Tomato Sauce, Mozzarella Cheese, Chicken, Mushroom',
    base_price: 1055,
    item_type: 'pizza',
    prices_json: { small: 665, medium: 1055, large: 1505 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_CHICKEN,
    name: 'Chicken Fajita',
    description: 'Tomato Sauce, Mozzarella Cheese, Chicken Fajita, Onion, Tomato',
    base_price: 1000,
    item_type: 'pizza',
    prices_json: { small: 665, medium: 1000, large: 1535 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_CHICKEN,
    name: 'Chicken Supreme',
    description: 'Tomato Sauce, Mozzarella Cheese, Onion, Turkey Ham, Chicken, Capsicum',
    base_price: 1130,
    item_type: 'pizza',
    prices_json: { small: 730, medium: 1130, large: 1535 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=600&q=80',
  },

  // --- FASTING PIZZA ---
  {
    category_id: CAT_FASTING,
    name: 'Tuna Pizza',
    description: 'Fasting Sauce, Tuna, Onion, Capsicum, Olives & Green Chilli',
    base_price: 740,
    item_type: 'pizza',
    prices_json: { small: 540, medium: 740, large: 1165 },
    dietary_tags: ['fasting'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_FASTING,
    name: 'Veggie Blast',
    description: 'Fasting Sauce, Pineapple, Onion, Olives, Capsicum, Tomato, Mushroom & Green Chilli',
    base_price: 795,
    item_type: 'pizza',
    prices_json: { small: 480, medium: 795, large: 1100 },
    dietary_tags: ['fasting'],
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_FASTING,
    name: 'Pineapple Lovers\'',
    description: 'Fasting Sauce, Pineapple, Mushroom, Tomato & Green Chilli',
    base_price: 740,
    item_type: 'pizza',
    prices_json: { small: 520, medium: 740, large: 1100 },
    dietary_tags: ['fasting'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
  },

  // --- SIDES & PASTA ---
  {
    category_id: CAT_SIDES,
    name: 'French Fries',
    description: 'Crispy golden french fries',
    base_price: 355,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Chilli Fries',
    description: 'Spicy seasoned french fries',
    base_price: 450,
    item_type: 'item',
    dietary_tags: ['spicy'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Cheesy Fries',
    description: 'French fries smothered in melted cheese',
    base_price: 425,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: '3 Bone-Out Wings',
    description: '3 pieces of crispy tender bone-out wings',
    base_price: 700,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: '6 Bone-Out Wings',
    description: '6 pieces of crispy tender bone-out wings',
    base_price: 1300,
    item_type: 'item',
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Plain Garlic Bread',
    description: 'Freshly baked garlic bread',
    base_price: 295,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Spicy Garlic Bread',
    description: 'Garlic bread topped with spicy seasoning',
    base_price: 445,
    item_type: 'item',
    dietary_tags: ['spicy'],
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Cheesy Garlic Bread',
    description: 'Garlic bread topped with melted mozzarella cheese',
    base_price: 445,
    item_type: 'item',
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Potato Wedge',
    description: 'Seasoned potato wedges',
    base_price: 360,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Hershey\'s Choco-Chip Cookies',
    description: 'Warm freshly baked Hershey chocolate chip cookie',
    base_price: 1930,
    item_type: 'item',
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Alfredo Pasta',
    description: 'Rich creamy alfredo pasta',
    base_price: 885,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281292?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Buffalo Chicken Wings',
    description: 'Crispy chicken wings tossed in spicy buffalo sauce',
    base_price: 1430,
    item_type: 'item',
    dietary_tags: ['spicy'],
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SIDES,
    name: 'Extra Cheese',
    description: 'Extra cheese topping',
    base_price: 225,
    item_type: 'item',
    prices_json: { small: 155, medium: 225, large: 405 },
    inventory_status: 'available',
    popular: false,
  },
  {
    category_id: CAT_SIDES,
    name: 'Extra Olive',
    description: 'Extra olives topping',
    base_price: 125,
    item_type: 'item',
    prices_json: { small: 95, medium: 125, large: 170 },
    inventory_status: 'available',
    popular: false,
  },
  {
    category_id: CAT_SIDES,
    name: 'Extra Pineapple',
    description: 'Extra pineapple topping',
    base_price: 170,
    item_type: 'item',
    prices_json: { small: 115, medium: 170, large: 270 },
    inventory_status: 'available',
    popular: false,
  },
  {
    category_id: CAT_SIDES,
    name: 'Extra Chicken',
    description: 'Extra chicken topping',
    base_price: 225,
    item_type: 'item',
    prices_json: { small: 150, medium: 225, large: 325 },
    inventory_status: 'available',
    popular: false,
  },
  {
    category_id: CAT_SIDES,
    name: 'Extra Beef',
    description: 'Extra beef topping',
    base_price: 175,
    item_type: 'item',
    prices_json: { small: 120, medium: 175, large: 405 },
    inventory_status: 'available',
    popular: false,
  },
  {
    category_id: CAT_SIDES,
    name: 'Chilli Sauce',
    description: 'Per pizza or slice',
    base_price: 100,
    item_type: 'item',
    dietary_tags: ['spicy'],
    inventory_status: 'available',
    popular: false,
  },
  {
    category_id: CAT_SIDES,
    name: 'Chilli Flakes',
    description: 'Chilli flakes container',
    base_price: 125,
    item_type: 'item',
    dietary_tags: ['spicy'],
    inventory_status: 'available',
    popular: false,
  },
  {
    category_id: CAT_SIDES,
    name: 'Italian Seasoning',
    description: 'Classic Italian herb seasoning',
    base_price: 100,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
  },

  // --- SPECIALS & MELTS ---
  {
    category_id: CAT_SPECIALS,
    name: 'Veggie Calzone',
    description: 'Folded pizza stuffed with veggies & cheese',
    base_price: 520,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SPECIALS,
    name: 'Beef Calzone',
    description: 'Folded pizza stuffed with seasoned beef & cheese',
    base_price: 635,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SPECIALS,
    name: 'Chicken Calzone',
    description: 'Folded pizza stuffed with chicken & cheese',
    base_price: 635,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SPECIALS,
    name: 'Big Boss Pizza',
    description: 'Giant rectangular party pizza for the whole group!',
    base_price: 5990,
    item_type: 'pizza',
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SPECIALS,
    name: 'Melts Spicy Chicken',
    description: 'Crispy folded pizza melts loaded with spicy chicken',
    base_price: 1220,
    item_type: 'item',
    dietary_tags: ['spicy'],
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SPECIALS,
    name: 'Melts Meat Lovers',
    description: 'Crispy folded pizza melts loaded with pepperoni, turkey ham & beef',
    base_price: 1270,
    item_type: 'item',
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_SPECIALS,
    name: 'Melts Pepperoni Lovers',
    description: 'Crispy folded pizza melts loaded with pepperoni & cheese',
    base_price: 1270,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  },

  // --- DRINKS ---
  {
    category_id: CAT_DRINKS,
    name: 'Coca-Cola',
    description: 'Refreshing Coca-Cola (300ml / 500ml)',
    base_price: 100,
    item_type: 'item',
    prices_json: { small: 100, medium: 140 },
    inventory_status: 'available',
    popular: true,
    image_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_DRINKS,
    name: 'Sprite',
    description: 'Crisp lemon-lime Sprite (300ml / 500ml)',
    base_price: 100,
    item_type: 'item',
    prices_json: { small: 100, medium: 140 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_DRINKS,
    name: 'Fanta Orange',
    description: 'Fruity Fanta Orange (300ml / 500ml)',
    base_price: 100,
    item_type: 'item',
    prices_json: { small: 100, medium: 140 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_DRINKS,
    name: 'Fanta Pineapple',
    description: 'Fruity Fanta Pineapple (300ml / 500ml)',
    base_price: 100,
    item_type: 'item',
    prices_json: { small: 100, medium: 140 },
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_DRINKS,
    name: 'Novida',
    description: 'Novida Apple Drink (300ml)',
    base_price: 100,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_DRINKS,
    name: 'Ambo Sparkling',
    description: 'Ambo Sparkling Mineral Water (500ml)',
    base_price: 110,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1560023907-5f313c8750b6?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_DRINKS,
    name: 'Ambo Flavor',
    description: 'Ambo Flavored Mineral Water (500ml)',
    base_price: 140,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1560023907-5f313c8750b6?auto=format&fit=crop&w=600&q=80',
  },
  {
    category_id: CAT_DRINKS,
    name: 'Water',
    description: 'Pure Mineral Water (500ml)',
    base_price: 70,
    item_type: 'item',
    inventory_status: 'available',
    popular: false,
    image_url: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
  },
];

async function seed() {
  console.log('Fetching existing categories...');
  const { data: existingCats } = await supabase.from('categories').select('*');
  const catMap = {};
  if (existingCats && existingCats.length > 0) {
    existingCats.forEach(c => {
      catMap[c.name.toLowerCase()] = c.id;
    });
  }

  const getCatId = (name, fallbackId) => {
    return catMap[name.toLowerCase()] || fallbackId;
  };

  const finalItems = ITEMS_DATA.map(item => {
    let catId = item.category_id;
    if (item.category_id === CAT_VEG) catId = getCatId('Veg Pizza', CAT_VEG);
    else if (item.category_id === CAT_MEAT) catId = getCatId('Meat Pizza', CAT_MEAT);
    else if (item.category_id === CAT_CHICKEN) catId = getCatId('Chicken Pizza', CAT_CHICKEN);
    else if (item.category_id === CAT_FASTING) catId = getCatId('Fasting Pizza', CAT_FASTING);
    else if (item.category_id === CAT_SIDES) catId = getCatId('Sides & Pasta', CAT_SIDES);
    else if (item.category_id === CAT_SPECIALS) catId = getCatId('Specials & Melts', CAT_SPECIALS);
    else if (item.category_id === CAT_DRINKS) catId = getCatId('Drinks', CAT_DRINKS);

    return { ...item, category_id: catId };
  });

  console.log(`Inserting ${finalItems.length} menu items...`);
  const { data, error: itemError } = await supabase.from('menu_items').insert(finalItems);
  if (itemError) {
    console.error('Item insert error:', itemError);
  } else {
    console.log('Successfully inserted all 56 menu items into Supabase!');
  }
}

seed();
